### ISSUE TITLE
macOS: unable to connect to redis cluster: `tcp: <addr>:<port>:connect: no route to host`

### ISSUE THREAD

**Issue by hhhapz** [redis/go-redis#3332]
## Expected Behavior

```go
package main

import (
	"context"
	"fmt"

	"github.com/redis/go-redis/v9"
)

var ctx = context.TODO()

func connectRegular(name string, addr string) {
	opt, err := redis.ParseURL(addr)
	if err != nil {
		panic(err)
	}

	client := redis.NewClient(opt)
	pong := client.Ping(ctx)
	if err := pong.Err(); err != nil {
		fmt.Printf("could not ping %s: %v\n", name, err)
		return
	}
	result, _ := pong.Result()
	fmt.Printf("ping result for %s: %v\n", name, result)
}

func connectClusters(urls ...string) {
	addrs := make([]string, len(urls))
	for i, addr := range urls {
		opt, err := redis.ParseURL(addr)
		if err != nil {
			panic(err)
		}
		addrs[i] = opt.Addr
	}

	opt := &redis.ClusterOptions{
		Addrs: addrs,
	}
	client := redis.NewClusterClient(opt)
	pong := client.Ping(ctx)
	if err := pong.Err(); err != nil {
		fmt.Printf("could not ping cluster: %v\n", err)
		return
	}
	result, _ := pong.Result()
	fmt.Printf("ping result for cluster: %v\n", result)
}

func main() {
	connectRegular("a", "redis://localhost:6379/0")
	connectRegular("b", "redis://localhost:6380/0")

	connectClusters("redis://localhost:6379/0", "redis://localhost:6380/0")
}
```

should output

```
ping result for a: PONG
ping result for b: PONG
ping result for cluster: PONG
```

## Current Behavior

```
ping result for a: PONG
ping result for b: PONG
ping result for cluster: dial tcp 192.168.97.7:6379: connect: no route to host
```

The redis cluster to connect on the last line, even if redis is able to connect to each host individually. 

## Steps to Reproduce

I am currently running redis via docker, with two instances using Orbstack and Docker Compose:
```
  cache:
    image: valkey/valkey:8.1
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    healthcheck:
      interval: 3s
      retries: 5
      test: ["CMD-SHELL", "valkey-cli ping || exit 1"]
      timeout: 5s
    ports:
      - 6379:6379
    profiles:
      - infra
    restart: on-failure

  cache-node-2:
    image: valkey/valkey:8.1
    command: ["--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    depends_on:
      - cache
    healthcheck:
      interval: 3s
      retries: 5
      test: ["CMD-SHELL", "valkey-cli ping || exit 1"]
      timeout: 5s
    ports:
      - 6380:6379
    profiles:
      - infra
    restart: on-failure
```

1. Run the script above
2. observe the output

## Context (Environment)

I have been able to reproduce this on a handful of different **macOS** machines.

## Detailed Description

We have this setup in a larger system in our interview repository available
in our `with-cache` branch:
https://github.com/autopilot-team/interview/blob/with-cache/backends/api/pkg/app/container.go#L196-L220

We have tested this with:
- Orbstack
- Macos 15.2.3
- Linux

And we can only reproduce this issue on MacOS, and not on Linux via docker compose.

I have no clue what is the source of the issue and what is specifically causing this, however I have been able to consistently reproduce this on different macOS devices from multiple different users.
